# Generated by Django 3.2.7 on 2021-11-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='asdasdasd', max_length=250),
            preserve_default=False,
        ),
    ]
