# Generated by Django 3.2.7 on 2021-11-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='latitude',
            field=models.FloatField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='longitude',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
