# Generated by Django 3.2.7 on 2021-11-20 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20211120_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 20, 2, 18, 57, 698408, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
